### ISSUE TITLE
addition of _FN for HAS_ARGS() in cpp_magic.h causes problems

### ISSUE THREAD

**Issue by timschmele** [18sg/uSHET#3]
Hey,
I tried the cpp_magic.h macros and found out, that the _FN suffix to the HAS_ARGS() functionality causes problems for me. Based on the version history, this seems to be the newest addition. Here is the error:

Pasting formed ')_FN', an invalid preprocessing token

When reverting to the old version, everything works. I believe the change fixes only the problem described by @RafaGago that caused the motivation for the change, but breaks everything else? Anyway, this change should be revised!

**Comment by mossblaser** [comment]
Thanks for spotting that! Bad me for not running tests when accepting that PR! The offending commit has been reverted in master and the test suite runs once more!
