### ISSUE TITLE
cpp_magic.h might be a cause for com.apple.dt.SourceKitService "runaway"

### ISSUE THREAD

**Issue by timschmele** [18sg/uSHET#4]
Hey, since I've been toying around with cpp_magic.h a bit, I noticed that using the macros in my source code make Xcode, specifically com.apple.dt.SourceKitService go crazy on me, taking up to 300% CPU. Now, this might just be a side effect of the recursion happening in the pre-processor code and Xcode trying to understand the code itself to show me the correct error messages (as it continually resolves pre-processor code already internally), but perhaps this is also linked to something that can be fixed?

I am not sure how to proceed on this issue, but I wanted to put this here, just for the record.

**Comment by mossblaser** [comment]
Hey there!

You might find changing the [eval macro](https://github.com/18sg/uSHET/blob/master/lib/cpp_magic.h#L73) to use fewer iterations may ease your pain. That said, I suspect your assessment is right and this is simply hitting a (rightly!) unoptimised path in the toolchain!

Btw, As always when I spot people using this curiosity overflows: what are you using this for? :)
